#! /bin/sh

## AUTOSTART
picom &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
sh $HOME/.fehbg &


## WORKSPACE
bspc monitor -d I II III IV V VI VII VIII IX X


## FRAMES AND GAPS
bspc config border_width	2
bspc config window_gap		12

bspc config normal_border_color		"#2B2F30"
bspc config active_border_color		"#2B2F30"
bspc config focused_border_color	"#383E40"


## THE COLOR OF THE SPACE WHEN SELECTING A NEW WINDOW
bspc config presel_feedback_color	"#CC0A0A"


## SEPARAION COEFFICIENT
bspc config split_ratio		0.5


## WINDOW FOCUS BY HOVERING THE CURSOR
bspc config focus_follows_pointer		true


## MONOCLE MODE WHEN ONE WINDOW IS OPEN
bspc config single_monocle	false


## DISABLING FRAME GAPS WHEN ONE WINDOW IS OPEN
bspc config borderless_monocle   false
bspc config gapless_monocle      false


## POINTER ACTION
bspc config pointer_modifier	mod4


## WINDOW RULES
bspc rule -a feh state=floating center=on
